import { Type } from '@angular/core';
import {
  ArrowRightIcon, ArrowLeftIcon, ChevronDownIcon, ChevronUpIcon, ChevronRightIcon,
  CloseIcon, MenuIcon, SearchIcon, CheckIcon, ExternalLinkIcon,
  GithubIcon, LinkedinIcon, TwitterIcon, YoutubeIcon,
  MailIcon, PhoneIcon, MapPinIcon, ClockIcon, GlobeIcon,
  DocumentIcon, RobotIcon, MicrophoneIcon, BookIcon, BriefcaseIcon,
  SparkleIcon, SunIcon, MoonIcon, StarIcon, HeartIcon,
  EyeIcon, DownloadIcon, UploadIcon, UserIcon, SettingsIcon,
  InfoIcon, WarningIcon, ErrorIcon, SuccessIcon
} from './icons/index';

/** Maps icon name strings to their standalone component types */
export const ICON_MAP: Record<string, Type<unknown>> = {
  'arrow-right':   ArrowRightIcon,
  'arrow-left':    ArrowLeftIcon,
  'chevron-down':  ChevronDownIcon,
  'chevron-up':    ChevronUpIcon,
  'chevron-right': ChevronRightIcon,
  'close':         CloseIcon,
  'menu':          MenuIcon,
  'search':        SearchIcon,
  'check':         CheckIcon,
  'external-link': ExternalLinkIcon,
  'github':        GithubIcon,
  'linkedin':      LinkedinIcon,
  'twitter':       TwitterIcon,
  'youtube':       YoutubeIcon,
  'mail':          MailIcon,
  'phone':         PhoneIcon,
  'map-pin':       MapPinIcon,
  'clock':         ClockIcon,
  'globe':         GlobeIcon,
  'document':      DocumentIcon,
  'robot':         RobotIcon,
  'microphone':    MicrophoneIcon,
  'book':          BookIcon,
  'briefcase':     BriefcaseIcon,
  'sparkle':       SparkleIcon,
  'sun':           SunIcon,
  'moon':          MoonIcon,
  'star':          StarIcon,
  'heart':         HeartIcon,
  'eye':           EyeIcon,
  'download':      DownloadIcon,
  'upload':        UploadIcon,
  'user':          UserIcon,
  'settings':      SettingsIcon,
  'info':          InfoIcon,
  'warning':       WarningIcon,
  'error':         ErrorIcon,
  'success':       SuccessIcon,
};
